import { L10n } from "@syncfusion/ej2-base";


L10n.load(
    {
        'fa-IR': {
           
            'grid': {
                "EmptyRecord": "اطلاعاتی یافت نشد",
                "True": "درست",
                "False": "نادرست",
                "InvalidFilterMessage": "فیلتر نامعتبر",
                "GroupDropArea": "برای گروه بندی، ستون مورد نظر را به این قسمت بکشید",
                "UnGroup": "برای لغو گروه بندی، بر روی علامت ضربدر کلید کنید",
                "GroupDisable": "گروه بندی برای این بخش غیر فعال است",
                "FilterbarTitle": "عنوان نوار فیلتر",
                "EmptyDataSourceError": "منبع دریافت اطلاعات خالی است",
                "Add": "افزودن",
                "Edit": "ویرایش",
                "Cancel": "انصراف",
                "Update": "بروز رسانی",
                "Delete": "حذف",
                "Print": "چاپ",
                "Pdfexport": "خروجی پی دی اف",
                "Excelexport": "خروجی اکسل",
                "Wordexport": "خروجی ورد",
                "Csvexport": "خروجی سی اس وی",
                "Search": "جستجو",
                "Columnchooser": "انتخاب کننده ستون",
                "Save": "ذخیره",
                "Item": "آیتم",
                "Items": "آیتم ها",
                "EditOperationAlert": "هیچ ردیفی برای ویرایش انتخاب نشده است",
                "DeleteOperationAlert": "هیج ردیفی برای حذف انتخاب نشده است",
                "SaveButton": "ذخیره",
                "OKButton": "تایید",
                "CancelButton": "انصراف",
                "EditFormTitle": "جزئیات ",
                "AddFormTitle": "افزودن ردیف جدید",
                "BatchSaveConfirm": "آیا از ذخیره کردن تغییرات مطمئن هستید؟",
                "BatchSaveLostChanges": "تغییراتی که ذخیره نشده اند از بین خواهند رفت، آیا مطمئن هستید؟",
                "ConfirmDelete": "آیا از حذف این آیتم مطمئن هستید؟",
                "CancelEdit": "آیا مطمئن هستید که نمی خواهید تغییرات را ذخیره کنید؟",
                "ChooseColumns": "ستون های مورد نظر را انتخاب کنید",
                "SearchColumns": "ستون برای جستجو",
                "Matchs": "نتیجه ای یافت نشد",
                "FilterButton": "فیلتر",
                "ClearButton": "خالی کردن",
                "StartsWith": "شروع با",
                "EndsWith": "خاتمه با",
                "Contains": "شامل",
                "Equal": "مساوی",
                "NotEqual": "نامساوی",
                "LessThan": "کوچکتر از",
                "LessThanOrEqual": "کوچکتر یا مساوی",
                "GreaterThan": "بزرگتر از",
                "GreaterThanOrEqual": "بزرگتر یا مساوی",
                "ChooseDate": "تاریخ را انتخاب کنید",
                "EnterValue": "مقدار مورد نظر را وارد کنید",
                "Copy": "کپی",
                "Group": "گروه بندی بر اساس این ستون",
                "Ungroup": "حذف گروه بندی بر اساس این ستون",
                "autoFitAll": "عرض ستون خودکار برای همه ستون ها",
                "autoFit": "تنظیم عرض خودکار برای این ستون",
                "Export": "خروجی گرفتن",
                "FirstPage": "صفحه اول",
                "LastPage": "صفحه آخر",
                "PreviousPage": "صفحه قبل",
                "NextPage": "صفحه بعد",
                "SortAscending": "مرتب سازی صعودی",
                "SortDescending": "مرتب سازی نزولی",
                "EditRecord": "ویرایش آیتم",
                "DeleteRecord": "حذف آیتم",
                "FilterMenu": "فیلتر"
            }, "checkboxFilter": {
                "Search": "جستجو",
                "OK": "تایید",
                "Cancel": "انصراف",
                "Filter": "فیلتر",
                "Clear": "خالی کردن",
                "SelectAll": "انتخاب همه",
                "Blanks": "خالی",
                "True": "درست",
                "False": "نادرست",
                "NoResult": "نتیجه ای یافت نشد"
            }, "excelFilter": {
                "ClearFilter": "خالی کردن فیلتر",
                "NumberFilter": "فیلتر عدد",
                "TextFilter": "فیلتر متن",
                "DateFilter": "فیلتر تاریخ",
                "MatchCase": "تطابق",
                "Equal": "مساوی",
                "NotEqual": "نامساوی",
                "LessThan": "کوچکتر از",
                "LessThanOrEqual": "کوچکتر یا مساوی",
                "GreaterThan": "بزرگتر از",
                "GreaterThanOrEqual": "بزرگتر یا مساوی",
                "Between": "بین",
                "CustomFilter": "فیلتر سفارشی",
                "StartsWith": "شروع با",
                "EndsWith": "خاتمه با",
                "Contains": "شامل",
                "OK": "تایید",
                "Cancel": "انصراف",
                "CustomFilterPlaceHolder": "یک مقدار وارد کنید",
                "CustomFilterDatePlaceHolder": "یک تاریخ وارد کنید",
                "AND": "و",
                "OR": "یا",
                "ShowRowsWhere": "نمایش ردیف ها به شرطی که:"
            }, "pager": {
                "currentPageInfo": "{0} از {1} صفحه",
                "totalItemsInfo": "({0} ردیف)",
                "firstPageTooltip": "به اولین صفحه برو",
                "lastPageTooltip": "به آخرین صفحه برو",
                "nextPageTooltip": "به صفحه بعد برو",
                "previousPageTooltip": "به صفحه قبل برو",
                "nextPagerTooltip": "به صفحه بعد برو",
                "previousPagerTooltip": "به پیجر قبل برو",
                "pagerDropDown": "ردیف در صفحه"
            },
            'dropdowns': {
                'actionFailureTemplate': "خطایی رخ داده است",
                'noRecordsTemplate': "آیتمی یافت نشد"
            },
        }

    });
